name: dead-simple-nodejs
branding:
  icon: archive
  color: green
description: Install fast & simply & with minimal dependencies
inputs:
  NODE_VERSION:
    description: nodejs version to install
    required: true
  NODE_DISTRO:
    description: nodejs distro to install
    default: linux-x64
    required: true
runs:
  using: composite
  steps:
    # https://github.com/nodejs/help/wiki/Installation
    # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
    - name: Install NodeJS
      shell: bash
      run: |
        sudo mkdir -p /usr/local/lib/nodejs
        pushd /usr/local/lib/nodejs

        curl https://nodejs.org/dist/v${{ inputs.NODE_VERSION }}/node-v${{ inputs.NODE_VERSION }}-${{ inputs.NODE_DISTRO }}.tar.xz | \
          sudo tar -xJ --strip-components=1

        popd

        echo '/usr/local/lib/nodejs/bin' >> $GITHUB_PATH
